const fs = require("fs");
const path = require("path");
const { resolveForPlugin } = require("./app-group.shared");

/**
 * Writes targets/widget/AppGroup.generated.swift so Swift matches JS/native entitlements.
 */
function withIosAppGroup(config) {
  const group = resolveForPlugin(config);
  const escaped = group.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
  const contents = `// Generated by withIosAppGroup — do not edit by hand.
// Value comes from app.config.js (EXPO_PUBLIC_IOS_APP_GROUP). Run: npx expo prebuild
import Foundation

enum AppGroupConstants {
    static let id: String = "${escaped}"
}
`;
  // Write to all iOS extension targets that share the App Group.
  const targets = ["widget", "notification-service"];
  for (const target of targets) {
    const outPath = path.join(__dirname, "targets", target, "AppGroup.generated.swift");
    fs.mkdirSync(path.dirname(outPath), { recursive: true });
    fs.writeFileSync(outPath, contents, "utf8");
  }
  return config;
}

module.exports = withIosAppGroup;
