require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
require File.join(File.dirname(`node --print "require.resolve('react-native/package.json')"`), "scripts/react_native_pods")

require 'json'
podfile_properties = JSON.parse(File.read(File.join(__dir__, 'Podfile.properties.json'))) rescue {}

def ccache_enabled?(podfile_properties)
  # Environment variable takes precedence
  return ENV['USE_CCACHE'] == '1' if ENV['USE_CCACHE']
  
  # Fall back to Podfile properties
  podfile_properties['apple.ccacheEnabled'] == 'true'
end

ENV['RCT_NEW_ARCH_ENABLED'] ||= '0' if podfile_properties['newArchEnabled'] == 'false'
ENV['EX_DEV_CLIENT_NETWORK_INSPECTOR'] ||= podfile_properties['EX_DEV_CLIENT_NETWORK_INSPECTOR']
ENV['RCT_USE_RN_DEP'] ||= '1' if podfile_properties['ios.buildReactNativeFromSource'] != 'true' && podfile_properties['newArchEnabled'] != 'false'
ENV['RCT_USE_PREBUILT_RNCORE'] ||= '1' if podfile_properties['ios.buildReactNativeFromSource'] != 'true' && podfile_properties['newArchEnabled'] != 'false'
platform :ios, podfile_properties['ios.deploymentTarget'] || '15.1'

prepare_react_native_project!

target 'InstantStatus' do
  use_expo_modules!

  if ENV['EXPO_USE_COMMUNITY_AUTOLINKING'] == '1'
    config_command = ['node', '-e', "process.argv=['', '', 'config'];require('@react-native-community/cli').run()"];
  else
    config_command = [
      'node',
      '--no-warnings',
      '--eval',
      'require(\'expo/bin/autolinking\')',
      'expo-modules-autolinking',
      'react-native-config',
      '--json',
      '--platform',
      'ios'
    ]
  end

  config = use_native_modules!(config_command)

  use_frameworks! :linkage => podfile_properties['ios.useFrameworks'].to_sym if podfile_properties['ios.useFrameworks']
  use_frameworks! :linkage => ENV['USE_FRAMEWORKS'].to_sym if ENV['USE_FRAMEWORKS']

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => podfile_properties['expo.jsEngine'] == nil || podfile_properties['expo.jsEngine'] == 'hermes',
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    :privacy_file_aggregation_enabled => podfile_properties['apple.privacyManifestAggregationEnabled'] != 'false',
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      :ccache_enabled => ccache_enabled?(podfile_properties),
    )
  
    # >>> withFmtFix
    fmt_cpp_flags = ['-DFMT_USE_CONSTEXPR=0', '-DFMT_USE_CONSTEVAL=0', '-Wno-invalid-constexpr']
    fmt_defines = ['FMT_USE_CONSTEXPR=0', 'FMT_USE_CONSTEVAL=0']

    apply_fmt_defines = lambda do |build_settings|
      existing_cpp = build_settings['OTHER_CPLUSPLUSFLAGS']
      cpp_flags =
        case existing_cpp
        when nil
          ['$(inherited)']
        when String
          [existing_cpp]
        else
          existing_cpp
        end

      fmt_cpp_flags.each do |flag|
        unless cpp_flags.include?(flag)
          cpp_flags << flag
        end
      end

      build_settings['OTHER_CPLUSPLUSFLAGS'] = cpp_flags

      existing_defs = build_settings['GCC_PREPROCESSOR_DEFINITIONS']
      defs =
        case existing_defs
        when nil
          ['$(inherited)']
        when String
          [existing_defs]
        else
          existing_defs
        end

      fmt_defines.each do |definition|
        unless defs.include?(definition)
          defs << definition
        end
      end

      build_settings['GCC_PREPROCESSOR_DEFINITIONS'] = defs
    end

    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        apply_fmt_defines.call(config.build_settings)
      end
    end

    updated_projects = {}
    installer.aggregate_targets.each do |aggregate_target|
      user_project = aggregate_target.user_project
      aggregate_target.user_targets.each do |user_target|
        user_target.build_configurations.each do |config|
          apply_fmt_defines.call(config.build_settings)
        end
      end
      updated_projects[user_project.path.to_s] = user_project
    end

    updated_projects.each_value(&:save)

    # Ensure fmt honors externally forced FMT_USE_CONSTEVAL in C++20 builds.
    fmt_base_h = File.join(installer.sandbox.root.to_s, 'fmt', 'include', 'fmt', 'base.h')
    if File.exist?(fmt_base_h)
      base_h_contents = File.read(fmt_base_h)
      unless base_h_contents.include?('#if defined(FMT_USE_CONSTEVAL)')
        base_h_contents = base_h_contents.sub(
          '#if !defined(__cpp_lib_is_constant_evaluated)',
          "#if defined(FMT_USE_CONSTEVAL)
// Use the provided definition.
#elif !defined(__cpp_lib_is_constant_evaluated)"
        )
        File.write(fmt_base_h, base_h_contents)
      end
    end
# <<< withFmtFix

  
    # Fix: folly/coro/Coroutine.h file not found (RN 0.74+)
    installer.pods_project.build_configurations.each do |config|
      config.build_settings['OTHER_CPLUSPLUSFLAGS'] ||= ['$(OTHER_CFLAGS)']
      config.build_settings['OTHER_CPLUSPLUSFLAGS'] << '-DFOLLY_CFG_NO_COROUTINES=1'
    end
end
end


# apple-targets-extension-loader -- Dynamic loading of target configurations
Dir.glob(File.join(__dir__, '..', 'targets', '**', 'pods.rb')).each do |target_file|
  target_name = File.basename(File.dirname(target_file))
  target target_name do
    # Create a new binding with access to necessary methods and variables
    target_binding = binding
    target_binding.local_variable_set(:podfile_properties, podfile_properties)

    # Evaluate the target file content in the new binding
    eval(File.read(target_file), target_binding, target_file)
  end
end
