// Generated by withIosAppGroup — do not edit by hand.
// Value comes from app.config.js (EXPO_PUBLIC_IOS_APP_GROUP). Run: npx expo prebuild
import Foundation

enum AppGroupConstants {
    static let id: String = "group.com.arda.instantstatus.dev"
}
