// MARK: - Generated
// This file is generated by scripts/generate-widget-storage-keys-swift.mjs
// from android-widget/widget-shared.ts. Do not edit by hand.
import Foundation

enum WidgetStorageKeys {
    static let widgetData: String = "widget_status_data"
    static let pendingTimelineReload: String = "widget_pending_timeline_reload"
    static let isPremium: String = "is_premium"
}
